export { default as HeroSection } from './HeroSection';
export { default as ArchaiveIntroSection } from './ArchaiveIntroSection';
export { default as BeforeAfterSection } from './BeforeAfterSection';
export { default as FeaturesSection } from './FeaturesSection';
export { default as ProcessSection } from './ProcessSection';
export { default as CaseSection } from './CaseSection';
export { default as NewsSection } from './NewsSection';
export { default as SecuritySection } from './SecuritySection';
export { default as CTASection } from './CTASection';
